### ISSUE TITLE
Problema con tf-nightly-2.0-preview en Mac OS X con python 3.72. 

### ISSUE THREAD

**Issue by pywirrarika** [beangoben/deep_learning_escuela_verano_19#2]
Problema con tf-nightly-2.0-preview en Mac OS X con python 3.72. 

Agrego el error que se genera a la salida[1]. Revisé y parece ser un problema abierto para la versión de python en cuestión y no ha sido corregido [2]. Alguna sugerencia para este caso? Tenemos que usar la última versión de TF? O también podríamos usar la versión estable más actual?

Manuel

[1]
Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement tf-nightly-2.0-preview (from -r /Users/elisabethalbinemagerhois/code/deep_learning_escuela_verano_19/condaenv.0_mhs8p2.requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tf-nightly-2.0-preview (from -r /Users/elisabethalbinemagerhois/code/deep_learning_escuela_verano_19/condaenv.0_mhs8p2.requirements.txt (line 1))

CondaEnvException: Pip failed

[2]https://github.com/tensorflow/tensorflow/issues/27470

**Comment by gibranfp** [comment]
¿Resolvería el problema si usamos `tensorflow=2.0.0-beta1`?

**Comment by pywirrarika** [comment]
Si no rompe nada esa versión, a mi me queda genial. Ya no tengo errores. Gracias!
